spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: dbspring
    username: dbspring
    url: jdbc:postgresql://localhost:5432/dbspring
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update

